[package]
name = "PKU-templates"
version = "0.0.1"
entrypoint = "lib.typ"
authors = ["PKU Typst 同好会 <https://github.com/pku-typst>"]
license = "MIT"
description = "PKU templates" 
repository = "https://github.com/pku-typst/PKU-typst-template"
keywords = ["template", "PKU"]
categories = ["report", "thesis"]
compiler = "0.11.0"
exclude = []
